#!/bin/bash

#help function
function help() {
    echo "$0 pull: pull emacs config from remote github repo."
    echo "$0 push: push local emacs config to remote github repo."
}

#do the pull work, pull remote configs and replace local configs
function dopull() {
    #delete Configs dir in current dir(if have)
    if [ -d "emsync" ]
    then
        rm -rf emsync
    fi

    #clone remote repo to local
    git clone https://github.com/hjiangsse/emsync.git

    #repalce
    cp ./emsync/emconf.tar.gz ~
    cd ~
    tar -xvzf emconf.tar.gz
    rm emconf.tar.gz
    cd -

    #clear
    rm -rf emsync
}

#do the push work, push local configs to remote repo on github
function dopush() {
    #delete Configs dir in current dir(if have)
    if [ -d "emsync" ]
    then
        rm -rf emsync
    fi

    #clone remote repo to local
    git clone https://github.com/hjiangsse/emsync.git

    #delete the old configs
    cd emsync
    ls -a | grep -v .git | xargs rm -r &> /dev/null

    #replace
    pw=$(pwd)
    echo ${pw}
    
    cd ~
    tar -cvzf emconf.tar.gz .emacs.d
    eval "mv emconf.tar.gz ${pw}"
    cd $pw

    git add *
    git commit -m "New commit"
    git push
    cd ..

    rm -rf emsync
}

if [ $# -ne 1 ]
then
    help
    exit 1
fi

if [ $1 == '-h' ] || [ $1 == '--help' ]
then
    help
    exit 0
fi

if [ $1 == "push" ]; then
    dopush
    exit 0
fi

if [ $1 == "pull" ]; then
    dopull
    exit 0
fi
