#!/bin/bash
git pull
echo "pull remote repository finish!"

git add *
echo "git add finish!"

DATETIME=`date "+%D %T"`
COMMITCMD="git commit -m \"${DATETIME}\""
eval $COMMITCMD
echo "git commit finish!"

git push
echo "push to remote repository finish!"
