#!/bin/bash

function help() {
    echo "$0 pull: pull emacs config from remote github repo."
    echo "$0 push: push local emacs config to remote github repo."
}

#do the pull work, pull remote configs and replace local configs
function dopull() {
    #delete Configs dir in current dir(if have)
    if [ -d "emsync" ]
    then
        rm -rf emsync
    fi

    #clone remote repo to local
    git clone https://github.com/hjiangsse/emsync.git

    #repalce
    mv ./emsync/.emacs.d ~/.emacs.d

    #clear
    rm -rf ./emsync/
}

#do the push work, push local configs to remote repo on github
function dopush() {
    #delete Configs dir in current dir(if have)
    if [ -d "Configs" ]
    then
        rm -rf Configs
    fi

    #clone remote repo to local
    git clone https://github.com/hjiangsse/emsync.git

    #delete the old configs
    rm -r emsync/*

    #replace
    cp -r ~/.emacs.d emsync/

    cd emsync
    git add *
    git commit -m "New commit"
    git push
    cd ..

    rm -rf emsync
}

if [ $# -ne 1 ]
then
    help
    exit 1
fi

if [ $1 == '-h' ] || [ $1 == '--help' ]
then
    help
    exit 0
fi

if [ $1 == "push" ]
then
    dopush
fi

if [ $1 == "pull" ]
then
    dopull
fi
