[package]
name = "fast_cal_offsets"
version = "0.1.0"
authors = ["hjiang <hjiang@sse.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.16.1"